/// 预置视频源和直播源（仅首次启动时seed，用户可编辑/删除）
library;

final List<Map<String, String>> defaultVideoSources = [
  {'name': '樱花资源', 'api': 'http://m3u8.apiyhzy.com/api.php/provide/vod'},
  {'name': '优质资源库', 'api': 'http://api.1080zyku.com/inc/api.php/provide/vod'},
  {'name': '闪电资源', 'api': 'http://sdzyapi.com/api.php/provide/vod/from/sdm3u8'},
  {'name': '红牛资源', 'api': 'http://hongniuzy2.com/api.php/provide/vod/from/hnm3u8'},
  {'name': 'U酷资源', 'api': 'http://api.ukuapi.com/api.php/provide/vod'},
  {'name': '卧龙资源', 'api': 'http://collect.wolongzyw.com/api.php/provide/vod'},
  {'name': '百度资源', 'api': 'http://api.apibdzy.com/api.php/provide/vod'},
  {'name': '量子资源', 'api': 'http://cj.lziapi.com/api.php/provide/vod/from/lzm3u8'},
  {'name': '天翼资源', 'api': 'https://www.911ysw.top/tianyi.php/provide/vod/'},
  {'name': '丫丫资源', 'api': 'https://cj.yayazy.net/api.php/provide/vod/'},
  {'name': '飘零影院', 'api': 'https://p2100.net/api.php/provide/vod/'},
  {'name': '无尽资源', 'api': 'https://api.wujinapi.me/api.php/provide/vod/'},
  {'name': '最大资源', 'api': 'http://zuidazy.me/api.php/provide/vod/'},
  {'name': '牛牛资源', 'api': 'https://api.niuniuzy.me/api.php/provide/vod/'},
  {'name': '360资源', 'api': 'https://360zy.com/api.php/provide/vod'},
  {'name': '极速资源', 'api': 'https://jszyapi.com/api.php/provide/vod/at/json'},
  {'name': '爱坤资源', 'api': 'https://ikunzyapi.com/api.php/provide/vod/'},
  {'name': '暴风资源', 'api': 'https://bfzyapi.com/api.php/provide/vod/'},
  {'name': '黑木耳', 'api': 'https://www.heimuer.tv/api.php/provide/vod'},
  {'name': '爱奇艺资源', 'api': 'https://iqiyizyapi.com/api.php/provide/vod'},
  {'name': '魔都资源', 'api': 'https://www.mdzyapi.com/api.php/provide/vod/'},
  {'name': '速播资源', 'api': 'https://subocj.com/api.php/provide/vod/at/json'},
  {'name': '天涯影视资源', 'api': 'https://tyyszyapi.com/api.php/provide/vod'},
  {'name': '旺旺短剧', 'api': 'https://wwzy.tv/api.php/provide/vod'},
  {'name': '小绵羊资源', 'api': 'https://vs.okcdn100.top/api.php/provide/vod/'},
  {'name': '金鹰资源', 'api': 'https://jyzyapi.com/provide/vod/from/jinyingm3u8'},
  {'name': '光速资源', 'api': 'https://api.guangsuapi.com/api.php/provide/vod/from/gsm3u8'},
  {'name': '金蝉资源', 'api': 'https://zy.jinchancaiji.com/api.php/provide/vod'},
  {'name': '猫眼资源', 'api': 'https://api.maoyanapi.top/api.php/provide/vod'},
  {'name': '淘片资源网', 'api': 'https://taopianapi.com/cjapi/mc/vod/json.html'},
];

/// 预置直播源（M3U格式）
final List<Map<String, String>> defaultLiveSources = [
  {'name': 'Guovin IPv4', 'url': 'https://raw.githubusercontent.com/Guovin/iptv-api/gd/output/ipv4/result.m3u'},
  {'name': 'zbds IPTV4', 'url': 'https://live.zbds.top/tv/iptv4.m3u'},
  {'name': '潇洒AI直播', 'url': 'https://raw.githubusercontent.com/PizazzGY/TV/master/output/user_result.m3u'},
  {'name': 'myIPTV IPv4', 'url': 'https://raw.githubusercontent.com/suxuang/myIPTV/refs/heads/main/ipv4.m3u'},
  {'name': 'Guovin 默认源', 'url': 'https://raw.githubusercontent.com/Guovin/iptv-api/gd/output/result.m3u'},
  {'name': 'BurningC4', 'url': 'https://raw.githubusercontent.com/BurningC4/Chinese-IPTV/master/TV-IPV4.m3u'},
  {'name': '茶客源', 'url': 'https://raw.githubusercontent.com/vamoschuck/TV/main/M3U'},
  {'name': 'Kimentanm', 'url': 'https://raw.githubusercontent.com/Kimentanm/aptv/master/m3u/iptv.m3u'},
  {'name': 'BigBigGrandG', 'url': 'https://raw.githubusercontent.com/BigBigGrandG/IPTV-URL/release/Gather.m3u'},
  {'name': 'EPG大陆频道', 'url': 'https://epg.pw/test_channels.m3u'},
  {'name': 'EPG香港频道', 'url': 'https://epg.pw/test_channels_hong_kong.m3u'},
  {'name': '虎牙一起看', 'url': 'https://live.freetv.top/huyayqk.m3u'},
  {'name': '斗鱼一起看', 'url': 'https://live.freetv.top/douyuyqk.m3u'},
];
